[package]
name = "ZenObservable"
version = "0.8.15-rc.4"
author = "Roblox"
content_root = "src"

[dependencies]
LuauPolyfill = "github.com/roblox/luau-polyfill@0.2.1"
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@2.1.1"
