[package]
name = "ZenObservable"
version = "0.1.0"
author = "Roblox"
content_root = "src"

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@=1.1.2"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.2.0"
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"
